const Lang = (function() {
  'use strict';
  let current = 'id';
  const strings = {
    id: {
      gameTitle: 'MONOPOLY',
      subtitle: 'Edisi Hardcore',
      play: 'BERMAIN',
      howToPlay: 'CARA BERMAIN',
      settings: 'PENGATURAN',
      createRoom: 'BUAT ROOM',
      joinRoom: 'GABUNG',
      roomCode: 'Kode Room',
      enterCode: 'Masukkan Kode Room',
      playerName: 'Nama Pemain',
      enterName: 'Masukkan Nama',
      selectCharacter: 'Pilih Karakter',
      ready: 'SIAP',
      notReady: 'BELUM SIAP',
      char_banker: 'Bankir',
      char_engineer: 'Insinyur', 
      char_trader: 'Pedagang',
      char_politician: 'Politikus',
      char_gambler: 'Penjudi',
      char_guardian: 'Penjaga',
      desc_banker: 'Bunga pinjaman lebih rendah. Aktif: Bekukan sewa properti lawan.',
      desc_engineer: 'Biaya bangun -20%. Aktif: Upgrade gratis instan.',
      desc_trader: 'Lihat tren saham lebih awal. Aktif: Paksa trading.',
      desc_politician: 'Bebas pajak. Aktif: Kenakan pajak 15% ke semua lawan.',
      desc_gambler: 'Lempar ulang dadu 1x/giliran. Aktif: Sewa 2x lipat 2 giliran.',
      desc_guardian: 'Kebal lelang paksa. Aktif: Shield lewati sewa 2x.',
      waitingPlayers: 'Menunggu Pemain...',
      addBot: 'Tambah Bot AI',
      startGame: 'MULAI PERMAINAN',
      rollDice: 'Lempar Dadu',
      buyProperty: 'Beli Properti',
      build: 'Bangun',
      trade: 'Tukar',
      auction: 'Lelang',
      stockMarket: 'Pasar Saham',
      loan: 'Pinjaman',
      blackMarket: 'Pasar Gelap',
      useSkill: 'Gunakan Skill',
      viewCards: 'Lihat Kartu',
      jointVenture: 'Joint Venture',
      endTurn: 'Akhiri Giliran',
      price: 'Harga',
      rent: 'Sewa',
      owner: 'Pemilik',
      mortgage: 'Gadai',
      unmortgage: 'Tebus Gadai',
      house: 'Rumah',
      hotel: 'Hotel',
      mall: 'Mall',
      hq: 'Markas',
      casino: 'Kasino',
      fortress: 'Benteng',
      evt_bullMarket: 'Pasar Bullish! Harga properti +30%, sewa +20%',
      evt_crash: 'KRISIS! Harga properti -40%, saham anjlok',
      evt_inflation: 'Inflasi! Semua biaya naik 25%',
      evt_constructionBoom: 'Boom Konstruksi! Biaya bangun -50%',
      evt_pandemic: 'Pandemi! Sewa -50%, trading dilarang',
      evt_techRevolution: 'Revolusi Teknologi! Revenue utility x3',
      evt_bailout: 'Bailout Pemerintah! Pemain termiskin dapat $500',
      evt_fire: 'Kebakaran! 1 properti random kehilangan bangunan',
      evt_goldRush: 'Demam Emas! Bonus GO x2',
      evt_disaster: 'Bencana Alam! Semua pemain bayar $200',
      evt_cyberWarfare: 'Perang Siber! Kerusakan sistem perbankan (-$150) & saham tech anjlok',
      evt_cryptoBoom: 'Ledakan Kripto! Dividen likuiditas +$300 & sewa kuantum +50%',
      evt_taxHoliday: 'Tax Holiday! Bebas pajak (0%) & diskon upgrade -30%',
      evt_megaMerger: 'Mega Merger! Sewa stasiun metro dan pembangkit listrik x2.5',
      evt_quantumGlitch: 'Anomali Kuantum! Cooldown skill semua pemain di-reset',
      evt_hyperInflation: 'Hiperinflasi! Sewa +40%, harga beli +50%, bonus GO $600',
      weather_sunny: 'Cerah ☀️ Sewa +15%',
      weather_rain: 'Hujan 🌧️ Sewa -20%',
      weather_storm: 'Badai ⛈️ Tidak bisa bangun',
      weather_fog: 'Kabut 🌫️ Info properti tersembunyi',
      weather_blizzard: 'Badai Salju ❄️ Langkah -2',
      weather_heatwave: 'Gelombang Panas 🔥 Utility x2',
      weather_clear: 'Langit Cerah 🌈 Bonus +10%',
      weather_aurora: 'Aurora Kuantum 🌌 Langkah +1, sewa sinergi distrik +25%',
      weather_acidRain: 'Hujan Asam 🧪 Tidak bisa bangun, biaya audit $30/bangunan',
      weather_solarEclipse: 'Gerhana Matahari 🌑 Pasar gelap diskon 25%, sewa -30%',
      weather_cyberSmog: 'Asap Siber 💨 Trading dinonaktifkan, revenue utility 1.5x',
      bankLoan: 'Pinjaman Bank (5%/giliran)',
      sharkLoan: 'Pinjaman Lintah (15%/giliran)',
      mortgageLoan: 'Gadai Properti (0%)',
      proposeTrade: 'Ajukan Penawaran',
      acceptTrade: 'Terima',
      rejectTrade: 'Tolak',
      counterOffer: 'Tawar Balik',
      currentBid: 'Tawaran Saat Ini',
      placeBid: 'Tawar',
      pass: 'Lewati',
      blindBid: 'Tawaran Tertutup',
      buy: 'Beli',
      sell: 'Jual',
      shares: 'Lembar',
      stockPrice: 'Harga Saham',
      spyDevice: 'Alat Mata-mata',
      counterfeit: 'Uang Palsu', 
      masterKey: 'Kunci Master',
      forgedDeed: 'Surat Palsu',
      protection: 'Perlindungan',
      stimulant: 'Stimulan',
      caught: 'TERTANGKAP!',
      proposeJV: 'Ajukan Joint Venture',
      dissolveJV: 'Bubarkan JV',
      splitRatio: 'Rasio Bagi Hasil',
      confirm: 'Konfirmasi',
      cancel: 'Batal',
      close: 'Tutup',
      back: 'Kembali',
      yes: 'Ya',
      no: 'Tidak',
      player: 'Pemain',
      turn: 'Giliran',
      round: 'Ronde',
      money: 'Uang',
      bankrupt: 'BANGKRUT!',
      winner: 'PEMENANG!',
      youWin: 'Kamu Menang!',
      gameOver: 'Permainan Berakhir',
      playerJoined: '{name} bergabung',
      playerLeft: '{name} keluar',
      propertyBought: '{name} membeli {prop}',
      rentPaid: '{name} membayar sewa ${amount} ke {owner}',
      buildingBuilt: '{name} membangun {type} di {prop}',
      cardDrawn: '{name} mengambil kartu',
      skillUsed: '{name} menggunakan skill!',
      jailIn: '{name} masuk penjara!',
      jailOut: '{name} keluar dari penjara',
      objectiveComplete: 'Misi Rahasia Selesai! +${reward}',
      foreclosure: 'Penyitaan! {name} kehilangan {prop}',
      dividendPaid: 'Dividen dibayarkan! +${amount}',
    },
    en: {
      gameTitle: 'MONOPOLY',
      subtitle: 'Hardcore Edition',
      play: 'PLAY',
      howToPlay: 'HOW TO PLAY',
      settings: 'SETTINGS',
      createRoom: 'CREATE ROOM',
      joinRoom: 'JOIN',
      roomCode: 'Room Code',
      enterCode: 'Enter Room Code',
      playerName: 'Player Name',
      enterName: 'Enter Name',
      selectCharacter: 'Select Character',
      ready: 'READY',
      notReady: 'NOT READY',
      char_banker: 'Banker',
      char_engineer: 'Engineer', 
      char_trader: 'Trader',
      char_politician: 'Politician',
      char_gambler: 'Gambler',
      char_guardian: 'Guardian',
      desc_banker: 'Lower loan interest. Active: Freeze opponent property rent.',
      desc_engineer: 'Build cost -20%. Active: Instant free upgrade.',
      desc_trader: 'See stock trends early. Active: Force trade.',
      desc_politician: 'Tax free. Active: Tax all opponents 15%.',
      desc_gambler: 'Reroll dice 1x/turn. Active: Double rent for 2 turns.',
      desc_guardian: 'Immune to forced auction. Active: Skip rent 2x.',
      waitingPlayers: 'Waiting for Players...',
      addBot: 'Add AI Bot',
      startGame: 'START GAME',
      rollDice: 'Roll Dice',
      buyProperty: 'Buy Property',
      build: 'Build',
      trade: 'Trade',
      auction: 'Auction',
      stockMarket: 'Stock Market',
      loan: 'Loan',
      blackMarket: 'Black Market',
      useSkill: 'Use Skill',
      viewCards: 'View Cards',
      jointVenture: 'Joint Venture',
      endTurn: 'End Turn',
      price: 'Price',
      rent: 'Rent',
      owner: 'Owner',
      mortgage: 'Mortgage',
      unmortgage: 'Unmortgage',
      house: 'House',
      hotel: 'Hotel',
      mall: 'Mall',
      hq: 'HQ',
      casino: 'Casino',
      fortress: 'Fortress',
      evt_bullMarket: 'Bull Market! Property price +30%, rent +20%',
      evt_crash: 'CRASH! Property price -40%, stocks plummet',
      evt_inflation: 'Inflation! All costs up 25%',
      evt_constructionBoom: 'Construction Boom! Build cost -50%',
      evt_pandemic: 'Pandemic! Rent -50%, trading banned',
      evt_techRevolution: 'Tech Revolution! Utility revenue x3',
      evt_bailout: 'Government Bailout! Poorest player gets $500',
      evt_fire: 'Fire! 1 random property loses buildings',
      evt_goldRush: 'Gold Rush! GO bonus x2',
      evt_disaster: 'Natural Disaster! All players pay $200',
      evt_cyberWarfare: 'Cyber Warfare! Bank systems hit (-$150) & tech stocks drop',
      evt_cryptoBoom: 'Crypto Boom! Cash dividend +$300 & Quantum rent +50%',
      evt_taxHoliday: 'Tax Holiday! Zero taxes (0%) & upgrade discount -30%',
      evt_megaMerger: 'Mega Merger! Metro stations & Power utilities rent x2.5',
      evt_quantumGlitch: 'Quantum Glitch! All players skill cooldowns instantly reset',
      evt_hyperInflation: 'Hyperinflation! Rent +40%, buy prices +50%, GO bonus $600',
      weather_sunny: 'Sunny ☀️ Rent +15%',
      weather_rain: 'Rain 🌧️ Rent -20%',
      weather_storm: 'Storm ⛈️ Cannot build',
      weather_fog: 'Fog 🌫️ Hidden property info',
      weather_blizzard: 'Blizzard ❄️ Movement -2',
      weather_heatwave: 'Heatwave 🔥 Utility x2',
      weather_clear: 'Clear Sky 🌈 Bonus +10%',
      weather_aurora: 'Quantum Aurora 🌌 Movement +1, district synergy rent +25%',
      weather_acidRain: 'Acid Rain 🧪 Cannot build, building audit cost $30',
      weather_solarEclipse: 'Solar Eclipse 🌑 Black Market 25% discount, rent -30%',
      weather_cyberSmog: 'Cyber Smog 💨 Trading disabled, utility revenue 1.5x',
      bankLoan: 'Bank Loan (5%/turn)',
      sharkLoan: 'Loan Shark (15%/turn)',
      mortgageLoan: 'Property Mortgage (0%)',
      proposeTrade: 'Propose Trade',
      acceptTrade: 'Accept',
      rejectTrade: 'Reject',
      counterOffer: 'Counter Offer',
      currentBid: 'Current Bid',
      placeBid: 'Place Bid',
      pass: 'Pass',
      blindBid: 'Blind Bid',
      buy: 'Buy',
      sell: 'Sell',
      shares: 'Shares',
      stockPrice: 'Stock Price',
      spyDevice: 'Spy Device',
      counterfeit: 'Counterfeit Money', 
      masterKey: 'Master Key',
      forgedDeed: 'Forged Deed',
      protection: 'Protection',
      stimulant: 'Stimulant',
      caught: 'CAUGHT!',
      proposeJV: 'Propose Joint Venture',
      dissolveJV: 'Dissolve JV',
      splitRatio: 'Split Ratio',
      confirm: 'Confirm',
      cancel: 'Cancel',
      close: 'Close',
      back: 'Back',
      yes: 'Yes',
      no: 'No',
      player: 'Player',
      turn: 'Turn',
      round: 'Round',
      money: 'Money',
      bankrupt: 'BANKRUPT!',
      winner: 'WINNER!',
      youWin: 'You Win!',
      gameOver: 'Game Over',
      playerJoined: '{name} joined',
      playerLeft: '{name} left',
      propertyBought: '{name} bought {prop}',
      rentPaid: '{name} paid ${amount} rent to {owner}',
      buildingBuilt: '{name} built {type} at {prop}',
      cardDrawn: '{name} drew a card',
      skillUsed: '{name} used a skill!',
      jailIn: '{name} went to jail!',
      jailOut: '{name} got out of jail',
      objectiveComplete: 'Secret Objective Complete! +${reward}',
      foreclosure: 'Foreclosure! {name} lost {prop}',
      dividendPaid: 'Dividends paid! +${amount}',
    }
  };
  
  function init(deps) {}
  
  function t(key, params) {
    let str = strings[current][key] || strings['en'][key] || key;
    if (params) {
      Object.keys(params).forEach(k => {
        str = str.replace('{'+k+'}', params[k]);
      });
    }
    return str;
  }
  
  function setLang(lang) {
    current = lang;
    if (typeof Events !== 'undefined') Events.emit('languageChanged', lang);
  }
  
  function getLang() {
    return current;
  }
  
  return { init, t, setLang, getLang, strings };
})();
